"""
OceanEmbed Phase 3 training script.

Works with the NPZ shards generated by preprocessing/build_dataset.py.

Current development dataset:
    5 channels -> set IN_CHANNELS=5 below.

Final dataset after winds:
    7 channels -> set IN_CHANNELS=7.

Expected shard format:
    X: (N, 9, 9, channels)
    y: (N, 15)

The training script transposes X to PyTorch's:
    (N, channels, 9, 9)
"""

from __future__ import annotations

import json
import math
import random
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset

from models.oceanembed_model import OceanEmbedModel


# =========================
# Configuration
# =========================

IN_CHANNELS = 5
EMBEDDING_DIM = 64
OUTPUT_DEPTHS = 15

BATCH_SIZE = 256
EPOCHS = 100
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4

PATIENCE = 10
MIN_DELTA = 1e-5

USE_DEPTH_WEIGHTED_LOSS = False

# Higher importance to the upper ocean.
# Depth order must match the 15 target levels.
DEPTHS_M = np.array(
    [0, 5, 10, 20, 30, 50, 75, 100, 125, 150, 200, 300, 500, 700, 1000],
    dtype=np.float32,
)

# Used only when depth-weighted loss is enabled.
# 0–200 m gets larger weights; deep levels get progressively less weight.
DEPTH_WEIGHTS = np.array(
    [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.8, 1.8,
     1.6, 1.6, 1.5, 1.0, 0.7, 0.5, 0.4],
    dtype=np.float32,
)

DATA_DIR = Path("data/processed")
CHECKPOINT_DIR = Path("models/checkpoints")
CHECKPOINT_PATH = CHECKPOINT_DIR / "best_model.pt"
PLOT_PATH = Path("training/loss_curve.png")
HISTORY_PATH = Path("training/history.json")

SEED = 42


# =========================
# Reproducibility
# =========================

def set_seed(seed: int = SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


# =========================
# Dataset
# =========================

class NPZShardDataset(Dataset):
    """
    Lazy shard dataset.

    It indexes shard files and loads only the shard containing the requested
    sample. This avoids loading every processed sample into RAM at startup.
    """

    def __init__(self, split: str):
        self.split = split
        self.files = sorted((DATA_DIR / split).glob("shard_*.npz"))

        if not self.files:
            raise FileNotFoundError(
                f"No NPZ shards found in {DATA_DIR / split}"
            )

        self.lengths = []
        self._cache_index = None
        self._cache_data = None

        for path in self.files:
            with np.load(path, allow_pickle=False) as data:
                self.lengths.append(len(data["X"]))

        self.offsets = np.cumsum([0] + self.lengths)

        print(
            f"{split}: {len(self.files)} shard(s), "
            f"{self.offsets[-1]} samples"
        )

    def __len__(self):
        return int(self.offsets[-1])

    def _load_shard(self, shard_index):
        if self._cache_index != shard_index:
            self._cache_data = np.load(
                self.files[shard_index],
                allow_pickle=False,
            )
            self._cache_index = shard_index
        return self._cache_data

    def __getitem__(self, index):
        shard_index = int(np.searchsorted(self.offsets, index, side="right") - 1)
        local_index = int(index - self.offsets[shard_index])

        data = self._load_shard(shard_index)

        x = data["X"][local_index]
        y = data["y"][local_index]

        # NPZ stores channels last: H,W,C.
        # PyTorch expects C,H,W.
        x = np.transpose(x, (2, 0, 1)).astype(np.float32)
        y = y.astype(np.float32)

        return torch.from_numpy(x), torch.from_numpy(y)


# =========================
# Loss
# =========================

class DepthWeightedMSELoss(nn.Module):
    def __init__(self, weights: np.ndarray):
        super().__init__()
        weights = torch.tensor(weights, dtype=torch.float32)
        self.register_buffer("weights", weights)

    def forward(self, prediction, target):
        squared_error = (prediction - target) ** 2
        return (squared_error * self.weights).mean()


def get_loss(device):
    if USE_DEPTH_WEIGHTED_LOSS:
        return DepthWeightedMSELoss(DEPTH_WEIGHTS).to(device)

    return nn.MSELoss()


# =========================
# Metrics
# =========================

def per_depth_rmse(predictions, targets):
    """
    Returns RMSE independently for every depth.
    Shape: (15,)
    """
    mse = np.mean((predictions - targets) ** 2, axis=0)
    return np.sqrt(mse)


# =========================
# Train / validation
# =========================

def run_epoch(model, loader, criterion, optimizer, device, training=True):
    if training:
        model.train()
    else:
        model.eval()

    total_loss = 0.0
    total_samples = 0

    predictions = []
    targets = []

    context = torch.enable_grad() if training else torch.no_grad()

    with context:
        for x, y in loader:
            x = x.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)

            embedding, prediction = model(x)
            loss = criterion(prediction, y)

            if training:
                optimizer.zero_grad(set_to_none=True)
                loss.backward()
                optimizer.step()

            batch_size = x.size(0)
            total_loss += loss.item() * batch_size
            total_samples += batch_size

            predictions.append(prediction.detach().cpu().numpy())
            targets.append(y.detach().cpu().numpy())

    avg_loss = total_loss / max(total_samples, 1)
    predictions = np.concatenate(predictions, axis=0)
    targets = np.concatenate(targets, axis=0)

    return avg_loss, per_depth_rmse(predictions, targets)


def save_checkpoint(
    model,
    optimizer,
    epoch,
    val_loss,
    channel_count,
):
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

    torch.save(
        {
            "epoch": epoch,
            "val_loss": val_loss,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "in_channels": channel_count,
            "embedding_dim": EMBEDDING_DIM,
            "output_depths": OUTPUT_DEPTHS,
            "depths_m": DEPTHS_M.tolist(),
        },
        CHECKPOINT_PATH,
    )


# =========================
# Main
# =========================

def main():
    set_seed()

    device = torch.device(
        "cuda" if torch.cuda.is_available() else "cpu"
    )

    print("=" * 60)
    print("OceanEmbed Phase 3")
    print("=" * 60)
    print(f"Device: {device}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")

    train_ds = NPZShardDataset("train")
    val_ds = NPZShardDataset("val")

    train_loader = DataLoader(
        train_ds,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
    )

    val_loader = DataLoader(
        val_ds,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
    )

    model = OceanEmbedModel(
        in_channels=IN_CHANNELS,
        embedding_dim=EMBEDDING_DIM,
        output_dim=OUTPUT_DEPTHS,
    ).to(device)

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
    )

    criterion = get_loss(device)

    parameter_count = sum(
        p.numel() for p in model.parameters() if p.requires_grad
    )

    print(f"Input channels: {IN_CHANNELS}")
    print(f"Embedding dimension: {EMBEDDING_DIM}")
    print(f"Trainable parameters: {parameter_count:,}")
    print(f"Depth-weighted loss: {USE_DEPTH_WEIGHTED_LOSS}")

    best_val_loss = math.inf
    epochs_without_improvement = 0

    history = {
        "train_loss": [],
        "val_loss": [],
        "val_rmse_by_depth": [],
    }

    for epoch in range(1, EPOCHS + 1):
        train_loss, train_rmse = run_epoch(
            model,
            train_loader,
            criterion,
            optimizer,
            device,
            training=True,
        )

        val_loss, val_rmse = run_epoch(
            model,
            val_loader,
            criterion,
            optimizer,
            device,
            training=False,
        )

        history["train_loss"].append(float(train_loss))
        history["val_loss"].append(float(val_loss))
        history["val_rmse_by_depth"].append(val_rmse.tolist())

        print(
            f"\nEpoch {epoch:03d} | "
            f"train_loss={train_loss:.6f} | "
            f"val_loss={val_loss:.6f}"
        )

        print("Validation RMSE by depth:")
        for depth, rmse in zip(DEPTHS_M, val_rmse):
            print(f"  {depth:>5.0f} m : {rmse:.4f}")

        if val_loss < best_val_loss - MIN_DELTA:
            best_val_loss = val_loss
            epochs_without_improvement = 0

            save_checkpoint(
                model,
                optimizer,
                epoch,
                val_loss,
                IN_CHANNELS,
            )

            print(f"  ✓ Saved best model -> {CHECKPOINT_PATH}")

        else:
            epochs_without_improvement += 1
            print(
                f"  No improvement "
                f"({epochs_without_improvement}/{PATIENCE})"
            )

            if epochs_without_improvement >= PATIENCE:
                print("Early stopping.")
                break

    PLOT_PATH.parent.mkdir(parents=True, exist_ok=True)
    HISTORY_PATH.parent.mkdir(parents=True, exist_ok=True)

    HISTORY_PATH.write_text(
        json.dumps(history, indent=2),
        encoding="utf-8",
    )

    plt.figure(figsize=(8, 5))
    plt.plot(history["train_loss"], label="Train")
    plt.plot(history["val_loss"], label="Validation")
    plt.xlabel("Epoch")
    plt.ylabel("MSE loss")
    plt.title("OceanEmbed training curve")
    plt.legend()
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(PLOT_PATH, dpi=150)
    plt.close()

    print("\nTraining complete.")
    print(f"Best checkpoint: {CHECKPOINT_PATH}")
    print(f"Loss curve: {PLOT_PATH}")
    print(f"History: {HISTORY_PATH}")


if __name__ == "__main__":
    main()